---
title: "Deskriptive Statistik"
author: "Lukas Steinke"
date: "05 12 2019"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(dplyr)
library(tidyverse)
library(ggplot2)
dataset <- readRDS("robo_pflege.rds")
dataset.short <- dataset[,c("age", "gender", "kut", "robo_wash", "human_wash")]
```
# Dies sind die desktiptiven Statistiken für den Datensatz.
Man sieht deskriptiv, dass die Probanden sich eher von einem Roboter, als von einem Menschen waschen lassen würden.

```{r warning=FALSE}
##Pipe
dataset_short <- dataset %>% select(robo_wash, human_wash)
dataset.short %>% psych::describe() %>% select(vars, mean, sd, median, min, max) 

##ohne Pipe
#psych::describe(select(dataset, age, gender, robo_wash, human_wash))

# Die Zeilen sind nicht gleich. Oben in Z22 selectest du Spalten aus dem describe(),
# unten selectest du Zeilen aus dataset und beschreibst diese alle. 
# Das macht das selbe wie Z22: select(psych::describe(dataset.short), vars, mean, sd, median, min, max) 

```
# Histogramme.

```{r warning=FALSE}
dataset %>% ggplot() +  aes(x = robo_wash) + geom_histogram(bins = 30, fill="red")
dataset %>% ggplot() +  aes(x = human_wash) + geom_histogram(bins = 30, fill="blue")

```