---
title: "Diagramm_SchmitzHolle"
author: "JS und MH"
date: "12/10/2019"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(devtools)
library(plotrix)
library(ggplot2)
library(ggthemes)
library(gdtools)
dataset <- readRDS("MaikeHolle/robo_pflege.rds")

devtools::install_github("HCIC/r-tools")

rwthfarben <- hcictools::rwth.colorpalette()

```

```{r}

dataset %>%
  filter(gender != "keine Angabe") %>%
  group_by(gender) %>%
  summarise(tv_m = mean(tv)-1, tv_sem = std.error(tv)) %>%
ggplot() +
 aes(x = gender, weight = tv_m, ymin = tv_m - tv_sem, ymax = tv_m + tv_sem, fill = gender) +
 geom_bar(fill = c(rwthfarben$lightblue, rwthfarben$red), width = 0.4) +
  geom_errorbar(width = 0.2) +
  scale_y_continuous(limits = c(0,5)) +
 labs(x = "Geschlecht",
      y = "Technikverständnis [0-5]",
      title = "Männer haben ein höheres Technikverständnis",
      subtitle = "Geschlechtsunterschiede im Säulendiagramm",
      caption = "Fehlerindikatoren zeigen Standardfehler des Mittelwerts.") +
 theme_fivethirtyeight() +
 NULL
```




  
  




