---
title: "Diagramme_DahmenFormannsWolters"
author: "JD and SF and FW"
date: "13 12 2019"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(devtools)
library(plotrix)
library(ggplot2)
library(ggthemes)

dataset <- readRDS("robo_pflege.rds")
devtools::install_github("HCIC/r-tools")
rwthfarben <- hcictools::rwth.colorpalette()

```

### Diagramm 1 (Geschlecht)

``` {r}
dataset %>% 
  filter(gender != "keine Angabe") %>%
  group_by(gender) %>%
  summarise(robo_m = mean(robo_hair_cut, na.rm = TRUE)-1, robo_sem = std.error(robo_hair_cut)) %>% 
  ggplot() +
  aes(x = gender, weight = robo_m, ymin = robo_m - robo_sem , ymax = robo_m + robo_sem, fill = gender) +
  geom_bar(fill = c(rwthfarben$lightblue, rwthfarben$red), width = 0.4) +
  geom_errorbar(width = 0.2) +
  scale_y_continuous(limits = c(0,5)) +
  labs(x = "Geschlecht",
      y = "Bereitschaft, sich von einem Roboter die Haare schneiden zu lassen",
      title = "M채nner w체rden sich eher von einem Roboter die Haare schneiden lassen als Frauen.",
      subtitle = "Geschlechtsunterschiede im S채ulendiagramm",
      caption = "Fehlerindikatoren zeigen Standardfehler des Mittelwerts.") +
 theme_linedraw() +
  NULL

ggsave("Diagramm_Geschlecht_neu.pdf", width = 9, height = 10)

```

### Diagramm 2 (Jobtyp)

``` {r}
dataset %>% 
  filter(job_type != "keine Angabe") %>%
  group_by(job_type) %>%
  summarise(robo2_m = mean(robo_hair_cut, na.rm = TRUE)-1, robo2_sem = std.error(robo_hair_cut)) %>% 
  ggplot() +
  aes(x = job_type, weight = robo2_m, ymin = robo2_m - robo2_sem , ymax = robo2_m + robo2_sem, fill = job_type) +
  geom_bar(fill = c(rwthfarben$red, rwthfarben$yellow, rwthfarben$green, rwthfarben$lightblue, rwthfarben$purple), width = 0.4) +
  geom_errorbar(width = 0.2) +
  scale_y_continuous(limits = c(0,5)) +
  labs(x = "Jobtyp",
      y = "Bereitschaft, sich von einem Roboter die Haare schneiden zu lassen",
      title = "Es gibt Unterschiede zwischen den Jobtypen in der Bereitschaft sich von einem Roboter die Haare schneiden zu lassen.",
      subtitle = "Unterschiede bzgl. Jobtypen im S채ulendiagramm",
      caption = "Fehlerindikatoren zeigen Standardfehler des Mittelwerts.") +
 theme_linedraw() +
  NULL

ggsave("Diagramm_Jobtyp_neu.pdf", width = 15, height = 10)

```