---
title: "Hausaufgabe - Deskriptive Statistik"
author: "JD and SF and FW"
date: "05 12 2019"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
library(ggplot2)
dataset <- readRDS("robo_pflege.rds")
dataset.short <- dataset[,c("age", "gender", "kut", "robo_hair_cut", "human_hair_cut")]
```

# Dies sind die desktiptiven Statistiken für den Datensatz.

Man sieht deskriptiv, dass sich die Probanden eher von einem Menschen, als von einem Roboter die Haare schneiden lassen würden. 

### mit Pipe

```{r warning=FALSE}
dataset.short %>% psych::describe() %>% select(vars, mean, sd, median, min, max) 
```

### ohne Pipe

```{r warning=FALSE}
#### select(psych::describe(dataset.short), vars, mean, sd, median, min, max)
```

# Histogramme.

```{r warning=FALSE}
dataset %>% ggplot() +  aes(x = robo_hair_cut) + geom_histogram(bins = 30, fill="red")

dataset %>% ggplot() +  aes(x = human_hair_cut) + geom_histogram(bins = 30, fill="blue")
```