---
title: "Hypothese 2 Berechnung"
output: html_document
---

Hypothese: Beruf und Familienstand beeinflussen den Stresspegel am Arbeitsplatz negativ. Verfahren: Three-way ANOVA. H0: Beruf und Familienstand haben keinen Einfluss auf den Stresspegel am Arbeitsplatz. H1: Beruf und Familienstand haben einen Einfluss auf den Stresspegel am Arbeitsplatz.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#ANOVA

library(jmv)
library(dataforsocialscience)
library(knitr)
library(tidyverse)
library(psych)



#raw.short



# schluesselliste <- list("Stress"= c("WLB.-Stress/Arbeit", "WLB.Stress/Umgang"))
# 
# scores <- scoreItems(schluesselliste, raw.short, missing= TRUE, min =1, max=6)
# 
# bind_cols(raw.short, as.tibble(scores$scores))

data <- readRDS("data/data.rds")
data <- data %>% 
  filter(Geschlecht != "divers")
data$Geschlecht <- fct_recode(data$Geschlecht,
               "männlich" = "divers")

data %>% 
  dplyr::filter(!is.na(Berufsstatus)) %>% 
  filter(!is.na(Familienstand.)) %>% 
  filter(!is.na(Geschlecht)) %>% 
  jmv::ANOVA(dep= "STRESS", factors= c("Berufsstatus", "Geschlecht"))

```

```{r}
  
jmv::ANOVA(dep= "STRESS", factors= c("Berufsstatus", "Familienstand."))

jmv::ANOVA(data, dep= "STRESS", factors= c("Geschlecht", "Berufsstatus"))


```


