---
title: "Diagramm_GaneshabalanStuhlmannKlein"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotrix)
library(devtools)
library(ggplot2)
library(ggthemes)


datensatz <- readRDS("robo_pflege.rds")
rwthfarben <- hcictools::rwth.colorpalette()


```



```{r}
devtools::install_github("HCIC/r-tools")
rwthfarben <- hcictools::rwth.colorpalette()


# Balkendiagramm (Jobtyp und robo_toilett)

datensatz %>% 
filter(job_type != "keine Angabe") %>% 
group_by(job_type) %>%   
summarise(robo_toilett_m = mean(robo_toilett, na.rm = TRUE)-1, robo_toilett_sem = std.error(robo_toilett)) %>% 

  ggplot() +
  aes(x = job_type, weight = robo_toilett_m, ymin = robo_toilett_m-robo_toilett_sem , ymax = robo_toilett_m+robo_toilett_sem, fill = job_type) +
  
  geom_bar(fill = c(rwthfarben$magenta, rwthfarben$petrol, rwthfarben$magenta, rwthfarben$petrol, rwthfarben$magenta)) +
  
  geom_errorbar(width = 0.5) +
  
  scale_y_continuous(limits = c(0,5)) +
 
  
  labs(x = "Jobtyp",
      y = "Anzahl der Zustimmungen",
      title = "Jobtyp nimmt keinen Einfluss auf die Akzeptanz", 
      subtitle = "Balkendiagramm zu den Jobtypen",
      caption = "Fehlerindikatoren zeigen Standardfehler für den Mittelwert an") +
 theme_fivethirtyeight()
NULL

ggsave("Diagramm_GaneshabalanStuhlmannKlein.pdf", width = 210, height = 297, units = "mm")

```







